services:
  go-worker:
    build: .
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - /var/lib/data-pipelines/results:/var/lib/data-pipelines/results
    environment:
      OUTPUT_DIR: /var/lib/data-pipelines/results
